DOCSP-39174 Add Restart Task Substep to Windows Instructions
mongodb/docs-relational-migrator pull request #131
Opened 2024-05-08 20:30 UTC by ianf-mongodb

## DESCRIPTION

Adding a requested restart command to the windows install instructions.

## STAGING

## JIRA

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663be077b67dbf804a31034a

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-05-09 14:35 UTC, ltran-mdb2 approved these changes
LGTM mod a small suggestion! Thanks @ianf-mongodb !

2024-05-09 14:35 UTC, ltran-mdb2 commented on source/includes/fact-restart-migrator-oracle-mysql-drivers.rst
> +   If you started Relational Migrator before copying the driver files
[suggestion] we could probably make this present tense

```suggestion
   If you start Relational Migrator before you copy the driver files 
```

2024-05-09 14:41 UTC, ianf-mongodb commented
Hi @tomhollander this came in as a support case this week so I wanted to get you to take a look in case you had anything to add.

2024-05-10 02:09 UTC, tomhollander requested changes
Thanks for proactively improving the docs here. However I think we can do a bit better here.

1. There's no reason why the format of the instructions should vary from one OS to the other. You've added a note box to 3/4 of the install instructions, there's no reason to treat Windows differently.
2. The note is a bit misleading as the need to restart isn't dependent on which database is being used. It would be more accurate to say something like "Relational Migrator must be restarted in order to load any drivers added to your Drivers folder."
3. These topics are related to installation, and if you actually follow them as written then the app won't be running at the time the drivers are copied over. While we should also accommodate users who copy drivers after starting the app, the steps should still be consistent.

So overall, across all 4 operating systems, I think the final step should be to _Start_ the application, but then you can add a note saying to _Restart_ if it was already running when you added the drivers.

2024-05-20 15:27 UTC, ianf-mongodb reviewed
Hi @tomhollander after reviewing I see your point and aligning the slight variations on each instruction set makes sense. To that end I added a final step to windows for double clicking the exe to start the add with the additional context note for the non-default drivers.

2024-05-21 00:26 UTC, tomhollander approved these changes

2024-05-22 18:10 UTC, merged