DOCSP-42513-correct-source-common-name
mongodb/docs-relational-migrator pull request #160
Opened 2024-08-13 19:56 UTC by ianf-mongodb

## DESCRIPTION

- Fixing naming error.

## STAGING

https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-42513/

## JIRA

https://jira.mongodb.org/browse/DOCSP-42513

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bbba398383957117cf6fff

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-08-13 19:58 UTC, ianf-mongodb commented
@tomhollander ready for review.

2024-08-14 17:16 UTC, tomhollander requested changes
@alwaysbemark should review this, but my understanding is that both `source` and `sink` settings exist, but we previously had `source` everywhere. The draft change has `sink` everywhere which also isn't correct.

2024-08-15 15:20 UTC, ianf-mongodb commented
Ok, I misunderstood the original ask, I have updated only the original section mentioned in the Jira ticket, could you verify this is correct @alwaysbemark? CC: @tomhollander

2024-08-16 12:59 UTC, alwaysbemark commented
Tom mentioned the fixes needed, otherwise LGTM!

2024-08-16 15:11 UTC, ianf-mongodb commented on source/installation/kafka-deployments/advanced-settings.txt
> +there is no retries after a retriable failure.
Updated.

2024-08-16 15:11 UTC, ianf-mongodb commented on source/installation/kafka-deployments/advanced-settings.txt
> +``migrator.connector.sink.common``. For example:
reverted

2024-08-16 15:24 UTC, tomhollander approved these changes

2024-08-19 20:46 UTC, merged