DOCSP-45120-change-sync-to-migration
mongodb/docs-relational-migrator pull request #180
Opened 2024-11-11 16:33 UTC by ltran-mdb2

## DESCRIPTION

## STAGING

## JIRA

## BUILD LOG

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-11-11 17:42 UTC, jmd-mongo reviewed
Thanks for these updates, @ltran-mdb2! Overall, this looks good and the replacements make sense. 

One question I have is about the `job` and `job_plural` constants defined in snooty.toml: should we use these replacements throughout? I don't see any cases where we're using `{+job+}` or `{+job_plural+}`. I think we should use these as much as makes sense, or consider removing them entirely.

Thanks,
Joe

2024-11-11 21:21 UTC, ltran-mdb2 commented
Thanks for your review @jmd-mongo ! Because the phrase "migration job" is used in so many forms throughout the docs (Migration Job, Migration Jobs, Migration job, migration job, migration jobs. etc), I removed the constants since there is not one form of the phrase that is overwhelmingly used.

2024-11-11 21:53 UTC, jmd-mongo approved these changes
Thanks, @ltran-mdb2! This one LGTM.

Thanks,
Joe

2024-11-12 16:09 UTC, ltran-mdb2 commented
Hi @tomhollander ! Would you be able to review this PR that changes all mentions of "sync job" to "migration job"?

2024-11-13 20:41 UTC, tomhollander requested changes
Missed one in a pretty crucial spot. LGTM otherwise.

2024-11-13 20:41 UTC, tomhollander commented on source/jobs/sync-jobs.txt
> +Migration jobs transfer data from your relational database to MongoDB. Sync
Missed one.

2024-11-14 21:15 UTC, tomhollander approved these changes

2024-11-14 21:36 UTC, merged