DOCSP-33246 Convert Views Content
mongodb/docs-relational-migrator pull request #63
Opened 2023-11-07 14:16 UTC by ianf-mongodb

## DESCRIPTION

## STAGING

## JIRA

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654a46aa5b686d6bd902c636

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2023-11-10 20:29 UTC, jeff-allen-mongo requested changes
@ianf-mongodb thanks for these updates. I left some suggestions for you to consider.

Jeff

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +        name. All views are selected for conversion by default.
Can we make this step more active voice?

To select the views to convert, click the (...). By default, all views are selected.

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +        The SQL code is loaded into the :guilabel:`Imported View`
```suggestion
        The SQL code is displayed in the :guilabel:`Imported View`
```

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +        displays in the :guilabel:`Converted MongoDB Query` pane.
```suggestion
        is displayed in the :guilabel:`Converted MongoDB Query` pane.
```

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +The query converter can convert your SQL views to MongoDB code.
I don't think we need this initial sentence.

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +The examples below show PostGreSQL views from the
```suggestion
The examples below show PostgreSQL views from the
```

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +The following example shows a ``inner join`` view converted to MongoDB:
```suggestion
The following example shows an ``inner join`` view converted to MongoDB:
```

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +The following example shows a ``inner join`` view converted to MongoDB:
[question]

Does "inner join" need to be monospaced?

2023-11-10 20:29 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +.. tabs::
I'm not sure the tabs are particularly helpful here. I think it's helpful to be able to see the input and output at once. Tabs would make sense if we were maybe showing different types of relational databases (in addition to Postgres), but I think in this case we might want to show both code-blocks together.

2023-11-10 20:31 UTC, jeff-allen-mongo commented on source/code-generation/query-converter/convert-views.txt
> +  :style: normal
Vale raised a false positive for this line. We created https://jira.mongodb.org/browse/DOCSP-34343 to investigate.

2023-11-10 21:35 UTC, ianf-mongodb reviewed
Thanks @jeff-allen-mongo, this has been updated and is ready for another look.

2023-11-13 14:01 UTC, jeff-allen-mongo approved these changes
LGTM

2023-11-13 19:14 UTC, ianf-mongodb commented
@tomhollander This is ready for review!

2023-11-13 23:19 UTC, tomhollander requested changes
Thanks, content looks good overall. However I think we need a bit of extra information to help people use the output.

The query converter takes the SQL query used to create the view and converts it to the equivalent MQL. If the user wants to create a MongoDB View from the query, they will need to take the pipeline from the `aggregate` command and pass it to the `createView` shell command - it would be great to have an example of this.

Alternatively, users may want to use the query in their code without creating a MongoDB view, in which case they can keep it as-is.

2023-11-14 21:44 UTC, ianf-mongodb reviewed
Hi @tomhollander, I added the additional createView code for each example on the page. The formatting on the code blocks might need some adjusting, but wanted to get your thoughts on the presentation as that can be cleaned up before publish.

2023-11-15 00:21 UTC, tomhollander approved these changes
Thanks for the updates!

2023-11-15 15:47 UTC, merged